use_frameworks!

platform :ios, '9.0'

target 'YUKAssociatedTypeRequirement_Example' do
  pod 'YUKAssociatedTypeRequirement', :path => '../'

  target 'YUKAssociatedTypeRequirement_Tests' do
    inherit! :search_paths

    
  end
end
